spring.application.name=Flight-Booking-App

spring.datasource.url= jdbc:postgresql://localhost:5432/FightDataBase
spring.datasource.username=postgres
spring.datasource.password=rachit21

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect